### ISSUE TITLE
Patch round 2

### ISSUE THREAD

**Issue by OgreTransporter** [shaunrd0/qtk#4]
### Division of the code
The division of the code is incorrect in my opinion. If you want to separate the code cleanly into a library and an application, then actually the MainWindow and the resources must go into the application and only the widget with the assimp and OpenGL classes into the library. Also, the scene needs to be assembled in the application and not in the library. Currently, I would therefore remove the library and directly create only an application. If you can separate models, scene and skybox cleanly from the application, you can build a library again and then also provide it with `Q_DECL_EXPORT`.

### Assimp interface
The assimp interface `assimp::assimp` seems to be wrong in the Ci version. I use a newer version under Windows and it is the other way round. To solve the problem, I simply added a switch for the target.

-----------------------------------------------------------------------------------------------------------------------------------------------
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 8b0d152..826b16b 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -27,30 +27,20 @@ if (NOT Qt6_FOUND)
   message(FATAL_ERROR "Specify path to Qt6 with `cmake -DCMAKE_PREFIX_PATH=/path/to/Qt/6.x.x/gcc_64 -S /path/to/qtk -B /path/to/qtk/build && cmake --build /path/to/qtk/build -j $(nprocs)`")
 endif()
 
-# Add our Qt resources.qrc file to our application
-set(SOURCES app/main.cpp)
-qt6_add_big_resources(SOURCES resources.qrc)
-
-add_executable(
-    qtk             # Executable name
-    ${SOURCES}      # Executable source code
-)
-
 ################################################################################
 # External Libraries
 ################################################################################
 
 # https://github.com/assimp/assimp/commit/6ac8279977c3a54118551e549d77329497116f66
 find_package(assimp REQUIRED)
-
+option(ASSIMP_NEW_INTERFACE "Use assimp::assimp as target instead of assimp" OFF)
 
 ################################################################################
-# Custom Libraries
+# Final Application
 ################################################################################
-
-# Mainwidget
-include(GenerateExportHeader)
-add_library(main-widget STATIC
+# Add our Qt resources.qrc file to our application
+set(SOURCES
+    app/main.cpp
     src/mainwidget.cpp src/mainwidget.h
     src/mainwindow.cpp src/mainwindow.h src/mainwindow.ui
     src/input.cpp src/input.h
@@ -65,29 +55,27 @@ add_library(main-widget STATIC
     src/scene.cpp src/scene.h
     src/resourcemanager.cpp src/resourcemanager.h
 )
-
-target_include_directories(main-widget PUBLIC src/)
-#if(TARGET assimp)
-target_link_libraries(main-widget PRIVATE assimp)
-#else()
-#    target_link_libraries(main-widget PRIVATE assimp::assimp)
-#endif()
-target_link_libraries(main-widget PUBLIC Qt6::OpenGLWidgets)
+qt6_add_big_resources(SOURCES resources.qrc)
+qt_add_executable(
+    qtk             # Executable name
+    ${SOURCES}      # Executable source code
+)
+target_include_directories(qtk PUBLIC src/)
+if(ASSIMP_NEW_INTERFACE)
+    target_link_libraries(qtk PRIVATE assimp::assimp)
+else()
+    target_link_libraries(qtk PRIVATE assimp)
+endif()
+target_link_libraries(qtk PRIVATE Qt6::OpenGLWidgets)
 if(WIN32)
     find_package(OpenGL REQUIRED)
-    target_link_libraries(main-widget PUBLIC OpenGL::GL)
+    target_link_libraries(qtk PRIVATE OpenGL::GL)
 endif()
 
-################################################################################
-# Final Application
-################################################################################
-
 # Link qtk executable to main main-widget library
-target_link_libraries(qtk PUBLIC main-widget)
-
 set_target_properties(qtk PROPERTIES
     WIN32_EXECUTABLE TRUE
     MACOSX_BUNDLE TRUE
+    MACOSX_BUNDLE_BUNDLE_VERSION ${PROJECT_VERSION}
+    MACOSX_BUNDLE_SHORT_VERSION_STRING ${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}
 )
-
-generate_export_header(main-widget)
```

**Comment by shaunrd0** [comment]
Thanks again for the contribution - I created a [branch](https://github.com/shaunrd0/qtk/commit/de87d1c40d9ef17f13a530ea9ff5b96afabe788e) with these changes, let me know if you have any edits. If not, I'll merge this weekend.

I think we need to keep the widget separate from the main application though. The idea was to separate it this way so I could support multiple views at the same time using widgets, and the current separation allows me to add qtk as a widget within Qt Designer and reposition it around other UI elements. Eventually I plan to add panels to see object and shader details, so this is a pretty useful feature. I think you're right about the poor separation of the code though - it could definitely be better.

You can add as many of these views as you want. You just open `mainwindow.ui` with Qt Designer, add an OpenGLWidget and promote it to `MainWidget` that was exported by `generate_export_header`.

![Screenshot_20220803_002455](https://user-images.githubusercontent.com/13367889/182525758-e2219756-494f-44fb-90b8-65c8abc84649.png)

**Comment by OgreTransporter** [comment]
I understand the idea behind creating a library for OpenGL+Assimp. But then only the widget and dependencies should be outsourced to the library. The Ui (MainWindow) should then become part of the main application. Also, it would make sense to move the creation of the scene to the application as well, because then you can use the widget multiple times with different content. If I have time, I will build a small demo.

**Comment by OgreTransporter** [comment]
I have started to separate the scene and the render widget. However, it is not finished yet.

https://github.com/OgreTransporter/QtAssimpOpenGlDemo

During the code rebuild, I also inadvertently fixed the skybox.

**Comment by shaunrd0** [comment]
Very cool, I really appreciate you taking the time to put this together. This will help a lot to improve the organization of the code.  The week is a bit busy but I do plan to work on this more over the weekend. I may have some time to mess with Windows CI tonight, and it seems you're heading in a good direction with code separation so I'll go ahead and merge the `dev` branch.

I'll likely try to build your demo and look over the code later, I'm looking forward to checking this out.
